[build]
base = "frontend"
command = "npm ci && npm run build"
publish = "frontend/build"

# SPA fallback so refreshes don't 404
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Proxy API calls to your PUBLIC backend (change the domain!)
[[redirects]]
from = "/api/*"
to = "https://your-backend-domain.com/:splat"
status = 200
force = true
