[build]
base = "frontend"
command = "npm ci && npm run build"
publish = "build"

# Proxy API to Cloud Run (FIRST)
[[redirects]]
from = "/api/*"
to = "https://bazuyuu-backend-4uz2zgyutq-as.a.run.app/:splat"
status = 200
force = true
headers = { X-Forwarded-Host = "bazuuyu.netlify.app" }

# SPA fallback (LAST)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
CI = "false"
